### ISSUE TITLE
Same effords

### ISSUE THREAD

**Issue by lucianodato** [werman/noise-suppression-for-voice#1]
Hi! I was working on doing an lv2 out of this library too but your project seems more ambitious. I couldn't work out the limitation of 48 Khz and 16 bit for the inputs. Did you had any luck with that? Are you resampling and quantizing before processing in order for it to work? I can thrash my project and collaborate with you if want. (Sorry I posted here I couldn't find your contact information, feel free to close this issue if you want)

**Comment by werman** [comment]
Hi! 
To be clear - I don't know much about sound processing and while I generally understand how the Xiph's library works I didn't do any modification to it.

So about inputs - when the input was lower than 48 Khz noise was still removed but with less accuracy, before I checked this I though to resample the input. It may yield better results but should be checked.

Because I mostly made the library for myself and because I'm not knowledgeable enough in sound processing I decided to stop at bare minimum and just make nice repository with relatively easy to follow instructions.

So in the end this project will not move anywhere or at least not by me, I think there will be something created out of original library by it's author but who knows... I'm just lacking knowledge in this field.

I may help if you'll want to make something more out of it (maybe you'll add Xiph's library as alternative processor to your project?) but every further improvement to the project is out of my knowledge - I know how to make games or website backends and don't know how create packages for linux repos or how to wrestle with pulseaudio which doesn't want my plugin to work without manually kicking it.

**Comment by lucianodato** [comment]
That's ok! No problem. Your work already helped me! I wasn't scaling to short values correctly. Now my plugin is working. From my test resampling gives pretty much the same result. RNNoise does much better as a VAD (vocal activity detector) than denoising algorithm. I can see how to integrate it to my other denoising plugin as that. Thank you very much! I can close this now.

**Comment by werman** [comment]
Good to know! If it's going to work even better with your plugin it would be awesome, I'll try it out in future.
