### ISSUE TITLE
Processing only part of frame.

### ISSUE THREAD

**Issue by masyagin1998** [werman/noise-suppression-for-voice#14]
Hello!
I know, that it isn't LADSPA forum, but I hope I will find here help.
I am new to LADSPA, so I really need it.
I tried to write analogue of your `noise-suppression-for-voice` for `webrtc-denoise` algo and found, that LADSPA expects, that `run()` method should return the same number of data as it got for input. Also I found your talk about it in on of Pull Requests.

So, do You know, is it possible, to use something like ring buffer for LADSPA plugins and return only already processed frames, so output can be less or bigger then input???

**Comment by werman** [comment]
Unfortunately I don't know much of sound processing, only slightly more than nothing. 

I think it would be tolerable if there is a small difference in sizes. 

If your problem is that you cannot chop the data into precisely integral amount of blocks for `webrtc-denoise`, you can carry the leftover to the next frame. But I cannot say how good it will sound...

**Comment by masyagin1998** [comment]
Thank You!
