### ISSUE TITLE
5ms delay

### ISSUE THREAD

**Issue by SeZuo** [werman/noise-suppression-for-voice#18]
Just tried this on video conference, the quality is amazing ! Thanks for your repo, it made this plugin very easy to try.

Now, the processing creates a noticeable delay in the signal, is there any way to reduce it ?

**Comment by werman** [comment]
You can try `latency_msec ` parameter of `module-loopback` https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/Modules/#module-loopback

Did you check delay with `pacmd list-sink-inputs`?

Also there is additional delay due to such convoluted setup, there is an issue opend in PulseAudio to create a single `module-ladspa-source` - https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/issues/120.

I didn't have the issue with latency with voice only, but, yes, as I know audio with video start feel wrong even with small desync.

**Comment by SeZuo** [comment]
`pacmd list-sink-inputs` gives a current latency of between 100ms and 200ms for the module-loopback. Setting `latency_msec=1` reduces this to 1~3ms.

I still hear a less than a second delay, probably around that 100ms mark.

I was using the stereo mode, but switching to mono does not improve this.

Thanks for the links, I added weight to that bug report in pulseaudio !

**Comment by siikamiika** [comment]
In addition to configuring `module-loopback` `latency_msec`, you can try reducing the default fragment amount and size in `/etc/pulse/daemon.conf`. I use the following values (defaults commented out):
```
; default-fragments = 4
; default-fragment-size-msec = 25
default-fragments = 2
default-fragment-size-msec = 4
```

**Comment by SeZuo** [comment]
Tested your settings. I hear no change. It's not easy to test small differences in delay. I do it with a loopback, by ear. If someone knows about a tool to test that more thoroughly, I'm ready to test.

**Comment by siikamiika** [comment]
I measured the latency of my bluetooth headphones so that I put them next to my mic together with wired headphones. The bluetooth headphones had `module-loopback` from the wired headphone sink. Then I compared the starting time of a short sound in Audacity and got ~220-250 ms.

In another test `module-remap-sink` and `module-loopback` with wired speakers adds ~13 ms for me.

In your case you could loopback both the plain mic and noise suppressed mic to the same sink, record its monitor and do the same. Not sure if the recording latency will vary between sources though.

**Comment by SeZuo** [comment]
Audacity only accepts a single input. Since the ladspa needs to be created against a (null) output and audacity is only created agains an existing input, it's impossible for me to link the two. Or I misunderstood something.

**Comment by SeZuo** [comment]
Tried something else :
Recorded the sound from my speakers (through optical denon amp) with a zoom mic, with very low latency. Recorded an 80 to 90ms delay through the filter, about ~40ms without.
Also, the filter prevents larsen.
