### ISSUE TITLE
How to choose (prefered) input device

### ISSUE THREAD

**Issue by mobergmann** [werman/noise-suppression-for-voice#200]
I have a setup with an Headset and a webcam, "unfortunately" does the Webcam has a microphone and this plugin seems to really like my webcam, as it always chooses it as the source/input device. I tried the "solution" in #120 (selecting my preferred source device and then choosing this plugin), but that didn't work. The webcam source was still used.
My current solution is to just unplug the camera when I don't need a webcam. This is unfortunately not an option when I am in an Meeting with my camera. Then the other participants have to listen to the bad audio quality of the webcam...

Is there a way to hint this plugin to prefer an input device and use that as long as it is available?

**Comment by pallaswept** [comment]
As per the thread you linked, this is a problem with your plugin host. This is a plugin and it does not choose or prefer or even know of a device to use. It just accepts audio in and pushes audio out. The "audio in" part of that, comes from the host.

It's probably best to close this issue (there is no problem here, and we don't want to overload the dev) and look to the documentation of your plugin host.

**Comment by mobergmann** [comment]
I just figured out how the answer in #120 was meant. I have to select my preferred input device as the system default (e.g. using the gnome system menu) and then I can select the Noise Canceling "Microphone" in the App of my choice (e.g. Jitsi, or Discord). I always had Noise Canceling selected as my system default and it therefore used the First other device available.

**Comment by pallaswept** [comment]
> I just figured out how the answer in #120 was meant. I have to select my preferred input device as the system default (e.g. using the gnome system menu) and then I can select the Noise Canceling "Microphone" in the App of my choice (e.g. Jitsi, or Discord). I always had Noise Canceling selected as my system default and it therefore used the First other device available.

That's odd. Normally, the whole idea of setting the default device, is to inform applications that they should use that device. So, if you set the "Noise Cancelling source" as your default in the Gnome menu, then jitsi or discord will use that as their input.

However, with the pipewire config given here, the "Noise Cancelling source" has no input target specified, so it should link to the default device, but the default device is itself, and it will not link to itself, so it has no input, so this would just give silence. One could resolve this by selecting the microphone as the target for the filter (in an app such as pavucontrol). This is probably the best way, because you only have to set the default, and this setting, and then every app will work without further configuration.

Alternatively, when you set the real mic as the default input device, the filter will link to that mic as it's input, so the "Noise Cancelling source" will provide the noise-suppressed audio from that mic. Then, you can select the "Noise Cancelling source" as the input in each application. This is not as simple as the above, because now you have to set the input device manually for every app, if you want them to get the noise-suppressed audio. By default, apps will use the real mic as input.

I hope this helps!
