### ISSUE TITLE
[PulseAudio] Chrome/Chromium doesn't work correctly with the plugin

### ISSUE THREAD

**Issue by werman** [werman/noise-suppression-for-voice#29]
It is observed that Chrome/Chromium doesn't work correctly with the monitor of null sink we create, not only it doesn't use it - it doesn't use the raw output of the mic.

Also see https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/issues/120

**Comment by lawl** [comment]
I've found stumbled across a solution for this [here](https://github.com/josh-richardson/cadmus/issues/11#issuecomment-651520937)

Running:

    pacmd load-module module-remap-source master=mic_denoised_out.monitor source_name=mic_remap source_properties="device.description='Denoised_Microphone'"

Creates an input source that I can just select in programs (instead of forcing it on them with `pavucontrol`. Side note: Couldn't get it to accept 'Denoise Microphone' with a space. But otherwise works fine for me.

**Comment by werman** [comment]
Thanks for letting me know!
